import { FieldType, FieldWidth, FormType, FieldOption } from "@/lib/types"

export interface TemplateField {
  field_type: FieldType
  label: string
  placeholder?: string
  help_text?: string
  is_required: boolean
  options?: FieldOption[]
  width: FieldWidth
  settings?: Record<string, unknown>
}

export interface FormTemplateDefinition {
  id: string
  name: string
  description: string
  category: "feedback" | "event_registration" | "application" | "survey" | "contact"
  form_type: FormType
  icon: string // lucide icon name
  fields: TemplateField[]
}

export const FORM_TEMPLATES: FormTemplateDefinition[] = [
  {
    id: "amasi-nextgen-feedback",
    name: "AMASI NextGen Feedback",
    description: "Official AMASI NextGen workshop feedback form with detailed session evaluation",
    category: "feedback",
    form_type: "feedback",
    icon: "ClipboardCheck",
    fields: [
      {
        field_type: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        is_required: true,
        width: "full",
      },
      {
        field_type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "radio",
        label: "How would you rate the overall organization of the workshop?",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "good", label: "Good" },
          { value: "average", label: "Average" },
          { value: "below_average", label: "Below Average" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "How would you rate the quality of the scientific sessions?",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "good", label: "Good" },
          { value: "average", label: "Average" },
          { value: "below_average", label: "Below Average" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "How would you rate the hands-on/practical sessions?",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "good", label: "Good" },
          { value: "average", label: "Average" },
          { value: "below_average", label: "Below Average" },
          { value: "poor", label: "Poor" },
          { value: "na", label: "Not Applicable" },
        ],
      },
      {
        field_type: "radio",
        label: "How would you rate the faculty/speakers?",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "good", label: "Good" },
          { value: "average", label: "Average" },
          { value: "below_average", label: "Below Average" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "How relevant was the content to your clinical practice?",
        is_required: true,
        width: "full",
        options: [
          { value: "highly_relevant", label: "Highly Relevant" },
          { value: "somewhat_relevant", label: "Somewhat Relevant" },
          { value: "neutral", label: "Neutral" },
          { value: "not_very_relevant", label: "Not Very Relevant" },
          { value: "not_relevant", label: "Not Relevant at All" },
        ],
      },
      {
        field_type: "radio",
        label: "How would you rate the venue and facilities?",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "good", label: "Good" },
          { value: "average", label: "Average" },
          { value: "below_average", label: "Below Average" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "How would you rate the food and hospitality?",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "good", label: "Good" },
          { value: "average", label: "Average" },
          { value: "below_average", label: "Below Average" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Would you recommend AMASI NextGen events to your colleagues?",
        is_required: true,
        width: "full",
        options: [
          { value: "definitely", label: "Definitely" },
          { value: "probably", label: "Probably" },
          { value: "not_sure", label: "Not Sure" },
          { value: "probably_not", label: "Probably Not" },
          { value: "definitely_not", label: "Definitely Not" },
        ],
      },
      {
        field_type: "radio",
        label: "How likely are you to attend future AMASI NextGen events?",
        is_required: true,
        width: "full",
        options: [
          { value: "very_likely", label: "Very Likely" },
          { value: "likely", label: "Likely" },
          { value: "neutral", label: "Neutral" },
          { value: "unlikely", label: "Unlikely" },
          { value: "very_unlikely", label: "Very Unlikely" },
        ],
      },
      {
        field_type: "textarea",
        label: "What did you like most about the event?",
        placeholder: "Share what you enjoyed the most...",
        is_required: false,
        width: "full",
      },
      {
        field_type: "textarea",
        label: "What suggestions do you have for improvement?",
        placeholder: "Your suggestions help us improve...",
        is_required: false,
        width: "full",
      },
      {
        field_type: "radio",
        label: "Overall, how would you rate this event?",
        is_required: true,
        width: "full",
        options: [
          { value: "5", label: "5 - Outstanding" },
          { value: "4", label: "4 - Very Good" },
          { value: "3", label: "3 - Good" },
          { value: "2", label: "2 - Fair" },
          { value: "1", label: "1 - Poor" },
        ],
      },
    ],
  },
  {
    id: "conference-registration",
    name: "Conference Registration",
    description: "Standard conference registration form with attendee details and preferences",
    category: "event_registration",
    form_type: "event_registration",
    icon: "UserPlus",
    fields: [
      {
        field_type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        is_required: true,
        width: "half",
      },
      {
        field_type: "phone",
        label: "Phone Number",
        placeholder: "+91 9876543210",
        is_required: true,
        width: "half",
      },
      {
        field_type: "text",
        label: "Institution / Organization",
        placeholder: "Enter your institution name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "text",
        label: "Designation",
        placeholder: "e.g., Professor, Resident, Consultant",
        is_required: true,
        width: "full",
      },
      {
        field_type: "select",
        label: "Dietary Preference",
        is_required: false,
        width: "half",
        options: [
          { value: "vegetarian", label: "Vegetarian" },
          { value: "non_vegetarian", label: "Non-Vegetarian" },
          { value: "vegan", label: "Vegan" },
          { value: "jain", label: "Jain" },
          { value: "no_preference", label: "No Preference" },
        ],
      },
      {
        field_type: "select",
        label: "T-Shirt Size",
        is_required: false,
        width: "half",
        options: [
          { value: "xs", label: "XS" },
          { value: "s", label: "S" },
          { value: "m", label: "M" },
          { value: "l", label: "L" },
          { value: "xl", label: "XL" },
          { value: "xxl", label: "XXL" },
        ],
      },
      {
        field_type: "textarea",
        label: "Special Requirements",
        placeholder: "Any accessibility needs, allergies, or other requirements...",
        is_required: false,
        width: "full",
      },
    ],
  },
  {
    id: "workshop-feedback",
    name: "Workshop Feedback",
    description: "Quick feedback form for workshops and training sessions",
    category: "feedback",
    form_type: "feedback",
    icon: "MessageSquare",
    fields: [
      {
        field_type: "text",
        label: "Name",
        placeholder: "Enter your name (optional)",
        is_required: false,
        width: "half",
      },
      {
        field_type: "email",
        label: "Email",
        placeholder: "your.email@example.com (optional)",
        is_required: false,
        width: "half",
      },
      {
        field_type: "rating",
        label: "Overall Rating",
        help_text: "Rate this workshop on a scale of 1-5",
        is_required: true,
        width: "full",
        settings: { max_rating: 5, rating_icon: "star" },
      },
      {
        field_type: "radio",
        label: "Was the content relevant to your needs?",
        is_required: true,
        width: "full",
        options: [
          { value: "very_relevant", label: "Very Relevant" },
          { value: "somewhat_relevant", label: "Somewhat Relevant" },
          { value: "not_relevant", label: "Not Relevant" },
        ],
      },
      {
        field_type: "radio",
        label: "How was the pace of the workshop?",
        is_required: true,
        width: "full",
        options: [
          { value: "too_fast", label: "Too Fast" },
          { value: "just_right", label: "Just Right" },
          { value: "too_slow", label: "Too Slow" },
        ],
      },
      {
        field_type: "radio",
        label: "Would you attend a follow-up session?",
        is_required: true,
        width: "full",
        options: [
          { value: "yes", label: "Yes" },
          { value: "maybe", label: "Maybe" },
          { value: "no", label: "No" },
        ],
      },
      {
        field_type: "textarea",
        label: "What did you find most valuable?",
        placeholder: "Tell us what worked well...",
        is_required: false,
        width: "full",
      },
      {
        field_type: "textarea",
        label: "Any suggestions for improvement?",
        placeholder: "Your feedback helps us improve...",
        is_required: false,
        width: "full",
      },
    ],
  },
  {
    id: "fmas-feedback",
    name: "FMAS Event Feedback",
    description: "Comprehensive feedback form for FMAS events covering course content, faculty, facilities, learning outcomes, and future course interests",
    category: "feedback",
    form_type: "feedback",
    icon: "ClipboardList",
    fields: [
      // Section 1: Course Content
      {
        field_type: "heading",
        label: "Course Content",
        is_required: false,
        width: "full",
        help_text: "Please rate the following aspects of the course content",
      },
      {
        field_type: "radio",
        label: "Relevance of topics covered",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Comprehensiveness of content",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Quality of presentation slides",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Quality of video demonstrations",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Balance between theory and practical aspects",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      // Section 2: Faculty
      {
        field_type: "heading",
        label: "Faculty",
        is_required: false,
        width: "full",
        help_text: "Please rate the faculty on the following parameters",
      },
      {
        field_type: "radio",
        label: "Subject knowledge",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Presentation skills",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Interaction with participants",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Ability to clarify doubts",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      // Section 3: Facilities and Organization
      {
        field_type: "heading",
        label: "Facilities and Organization",
        is_required: false,
        width: "full",
        help_text: "Please rate the following aspects",
      },
      {
        field_type: "radio",
        label: "Registration process",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Venue facilities",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Audio-visual arrangements",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Refreshments/meals",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "Time management",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "very_good", label: "Very Good" },
          { value: "good", label: "Good" },
          { value: "poor", label: "Poor" },
        ],
      },
      // Section 4: Open-ended Feedback
      {
        field_type: "textarea",
        label: "Any sessions that could be improved",
        placeholder: "Please describe any sessions you feel could be improved...",
        is_required: true,
        width: "full",
      },
      // Learning Outcomes
      {
        field_type: "heading",
        label: "Learning Outcomes",
        is_required: false,
        width: "full",
      },
      {
        field_type: "textarea",
        label: "What are the key skills/knowledge you gained from this course?",
        placeholder: "Describe the key skills or knowledge you gained...",
        is_required: true,
        width: "full",
      },
      {
        field_type: "textarea",
        label: "How do you plan to implement these in your practice?",
        placeholder: "Describe how you plan to apply what you learned...",
        is_required: true,
        width: "full",
      },
      // Suggestions for Improvement
      {
        field_type: "heading",
        label: "Suggestions for Improvement",
        is_required: false,
        width: "full",
      },
      {
        field_type: "textarea",
        label: "What additional topics would you like to see covered in future courses?",
        placeholder: "Suggest topics for future courses...",
        is_required: true,
        width: "full",
      },
      {
        field_type: "textarea",
        label: "How can we improve the course experience?",
        placeholder: "Share your suggestions for improvement...",
        is_required: true,
        width: "full",
      },
      // Future Courses
      {
        field_type: "heading",
        label: "Future Courses",
        is_required: false,
        width: "full",
      },
      {
        field_type: "radio",
        label: "Would you recommend this course to colleagues?",
        is_required: true,
        width: "full",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
      {
        field_type: "radio",
        label: "Are you interested in attending advanced MAS courses in the future?",
        is_required: true,
        width: "full",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
      {
        field_type: "textarea",
        label: "Specific areas of interest for future courses",
        placeholder: "Tell us what areas you'd like future courses to cover...",
        is_required: true,
        width: "full",
      },
      {
        field_type: "textarea",
        label: "Any Other Comments",
        placeholder: "Share any additional comments or feedback...",
        is_required: true,
        width: "full",
      },
    ],
  },
  {
    id: "speaker-application",
    name: "Speaker / Faculty Application",
    description: "Application form for speakers and faculty to submit their profiles and topics",
    category: "application",
    form_type: "application",
    icon: "Mic",
    fields: [
      {
        field_type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        is_required: true,
        width: "half",
      },
      {
        field_type: "phone",
        label: "Phone Number",
        placeholder: "+91 9876543210",
        is_required: true,
        width: "half",
      },
      {
        field_type: "text",
        label: "Institution / Organization",
        placeholder: "Enter your institution name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "text",
        label: "Designation",
        placeholder: "e.g., Professor, HOD, Consultant",
        is_required: true,
        width: "full",
      },
      {
        field_type: "textarea",
        label: "Brief Bio",
        placeholder: "A short professional biography (100-200 words)",
        help_text: "This may be used in event materials",
        is_required: true,
        width: "full",
      },
      {
        field_type: "text",
        label: "Proposed Topic",
        placeholder: "Title of your talk/presentation",
        is_required: true,
        width: "full",
      },
      {
        field_type: "textarea",
        label: "Abstract",
        placeholder: "Brief summary of your proposed presentation (200-300 words)",
        is_required: true,
        width: "full",
      },
      {
        field_type: "select",
        label: "Preferred Format",
        is_required: true,
        width: "half",
        options: [
          { value: "lecture", label: "Lecture" },
          { value: "workshop", label: "Workshop / Hands-on" },
          { value: "panel", label: "Panel Discussion" },
          { value: "live_demo", label: "Live Demo / Surgery" },
          { value: "any", label: "Any Format" },
        ],
      },
      {
        field_type: "select",
        label: "Availability",
        is_required: true,
        width: "half",
        options: [
          { value: "all_days", label: "All Days" },
          { value: "day_1", label: "Day 1 Only" },
          { value: "day_2", label: "Day 2 Only" },
          { value: "flexible", label: "Flexible" },
        ],
      },
    ],
  },
  {
    id: "post-event-feedback",
    name: "Post-Event Feedback Survey",
    description: "Anonymous post-event feedback survey to gather honest attendee insights and satisfaction scores",
    category: "feedback",
    form_type: "feedback",
    icon: "BarChart3",
    fields: [
      {
        field_type: "select",
        label: "Age Group",
        is_required: false,
        width: "half",
        options: [
          { value: "under_25", label: "Under 25" },
          { value: "25_34", label: "25-34" },
          { value: "35_44", label: "35-44" },
          { value: "45_54", label: "45-54" },
          { value: "55_plus", label: "55+" },
        ],
      },
      {
        field_type: "select",
        label: "How did you hear about this event?",
        is_required: false,
        width: "half",
        options: [
          { value: "email", label: "Email Invite" },
          { value: "whatsapp", label: "WhatsApp" },
          { value: "social_media", label: "Social Media" },
          { value: "colleague", label: "Colleague / Word of Mouth" },
          { value: "website", label: "Website" },
          { value: "other", label: "Other" },
        ],
      },
      {
        field_type: "rating",
        label: "Overall Event Rating",
        help_text: "Rate this event on a scale of 1-5",
        is_required: true,
        width: "full",
        settings: { max_rating: 5, rating_icon: "star" },
      },
      {
        field_type: "scale",
        label: "How likely are you to recommend this event to a colleague?",
        help_text: "0 = Not at all likely, 10 = Extremely likely",
        is_required: true,
        width: "full",
        settings: { min: 0, max: 10, min_label: "Not likely", max_label: "Extremely likely" },
      },
      {
        field_type: "textarea",
        label: "What was your favourite part of the event?",
        placeholder: "Tell us what you enjoyed the most...",
        is_required: false,
        width: "full",
      },
      {
        field_type: "radio",
        label: "How would you rate the speakers/faculty?",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "good", label: "Good" },
          { value: "average", label: "Average" },
          { value: "below_average", label: "Below Average" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "radio",
        label: "How would you rate the venue and logistics?",
        is_required: true,
        width: "full",
        options: [
          { value: "excellent", label: "Excellent" },
          { value: "good", label: "Good" },
          { value: "average", label: "Average" },
          { value: "below_average", label: "Below Average" },
          { value: "poor", label: "Poor" },
        ],
      },
      {
        field_type: "textarea",
        label: "What could we improve for the next event?",
        placeholder: "Your suggestions help us improve...",
        is_required: false,
        width: "full",
      },
      {
        field_type: "radio",
        label: "Would you attend future events?",
        is_required: true,
        width: "full",
        options: [
          { value: "definitely", label: "Definitely" },
          { value: "probably", label: "Probably" },
          { value: "not_sure", label: "Not Sure" },
          { value: "probably_not", label: "Probably Not" },
        ],
      },
    ],
  },
  {
    id: "workshop-registration",
    name: "Workshop Registration",
    description: "Registration form for hands-on workshops with experience level and session preferences",
    category: "event_registration",
    form_type: "event_registration",
    icon: "GraduationCap",
    fields: [
      {
        field_type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        is_required: true,
        width: "half",
      },
      {
        field_type: "phone",
        label: "Phone Number",
        placeholder: "+91 9876543210",
        is_required: true,
        width: "half",
      },
      {
        field_type: "text",
        label: "Institution / Hospital",
        placeholder: "Enter your institution name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "select",
        label: "Designation",
        is_required: true,
        width: "half",
        options: [
          { value: "consultant", label: "Consultant" },
          { value: "senior_resident", label: "Senior Resident" },
          { value: "junior_resident", label: "Junior Resident" },
          { value: "fellow", label: "Fellow" },
          { value: "professor", label: "Professor" },
          { value: "other", label: "Other" },
        ],
      },
      {
        field_type: "select",
        label: "Experience Level",
        is_required: true,
        width: "half",
        options: [
          { value: "beginner", label: "Beginner - No prior experience" },
          { value: "intermediate", label: "Intermediate - Some experience" },
          { value: "advanced", label: "Advanced - Extensive experience" },
        ],
      },
      {
        field_type: "textarea",
        label: "What do you hope to learn from this workshop?",
        placeholder: "Describe your learning objectives...",
        is_required: false,
        width: "full",
      },
      {
        field_type: "textarea",
        label: "Special Requirements",
        placeholder: "Any accessibility needs, allergies, or other requirements...",
        is_required: false,
        width: "full",
      },
    ],
  },
  {
    id: "sponsorship-application",
    name: "Sponsorship Application",
    description: "Application form for sponsors and exhibitors with tier selection and company details",
    category: "application",
    form_type: "application",
    icon: "Building2",
    fields: [
      {
        field_type: "heading",
        label: "Company Information",
        is_required: false,
        width: "full",
      },
      {
        field_type: "text",
        label: "Company / Organization Name",
        placeholder: "Enter company name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "text",
        label: "Contact Person Name",
        placeholder: "Primary point of contact",
        is_required: true,
        width: "full",
      },
      {
        field_type: "email",
        label: "Email Address",
        placeholder: "contact@company.com",
        is_required: true,
        width: "half",
      },
      {
        field_type: "phone",
        label: "Phone Number",
        placeholder: "+91 9876543210",
        is_required: true,
        width: "half",
      },
      {
        field_type: "text",
        label: "Website",
        placeholder: "https://www.company.com",
        is_required: false,
        width: "full",
      },
      {
        field_type: "heading",
        label: "Sponsorship Details",
        is_required: false,
        width: "full",
      },
      {
        field_type: "radio",
        label: "Sponsorship Tier",
        is_required: true,
        width: "full",
        options: [
          { value: "platinum", label: "Platinum Sponsor" },
          { value: "gold", label: "Gold Sponsor" },
          { value: "silver", label: "Silver Sponsor" },
          { value: "exhibitor", label: "Exhibitor Only" },
        ],
      },
      {
        field_type: "checkboxes",
        label: "Interested in",
        is_required: false,
        width: "full",
        options: [
          { value: "exhibition_booth", label: "Exhibition Booth" },
          { value: "brochure_insert", label: "Brochure / Kit Insert" },
          { value: "session_sponsorship", label: "Session / Workshop Sponsorship" },
          { value: "lunch_dinner", label: "Lunch / Dinner Sponsorship" },
          { value: "badge_lanyard", label: "Badge / Lanyard Branding" },
          { value: "live_demo", label: "Product Demo / Live Surgery Support" },
        ],
      },
      {
        field_type: "textarea",
        label: "Additional Requirements or Comments",
        placeholder: "Any specific needs such as booth size, power requirements, special setup...",
        is_required: false,
        width: "full",
      },
    ],
  },
  {
    id: "abstract-submission",
    name: "Abstract Submission",
    description: "Scientific abstract submission form for papers, posters, and video presentations",
    category: "application",
    form_type: "application",
    icon: "FileSearch",
    fields: [
      {
        field_type: "heading",
        label: "Presenter Details",
        is_required: false,
        width: "full",
      },
      {
        field_type: "text",
        label: "Presenting Author Name",
        placeholder: "Enter the presenting author's full name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        is_required: true,
        width: "half",
      },
      {
        field_type: "phone",
        label: "Phone Number",
        placeholder: "+91 9876543210",
        is_required: true,
        width: "half",
      },
      {
        field_type: "text",
        label: "Institution / Affiliation",
        placeholder: "Enter your institution name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "text",
        label: "Co-Authors",
        placeholder: "e.g., Dr. A Kumar, Dr. B Sharma",
        help_text: "Comma-separated list of co-author names",
        is_required: false,
        width: "full",
      },
      {
        field_type: "heading",
        label: "Abstract Details",
        is_required: false,
        width: "full",
      },
      {
        field_type: "text",
        label: "Abstract Title",
        placeholder: "Enter the title of your abstract",
        is_required: true,
        width: "full",
      },
      {
        field_type: "select",
        label: "Presentation Type",
        is_required: true,
        width: "half",
        options: [
          { value: "oral", label: "Oral Presentation" },
          { value: "poster", label: "Poster Presentation" },
          { value: "video", label: "Video Presentation" },
          { value: "case_report", label: "Case Report" },
        ],
      },
      {
        field_type: "select",
        label: "Category / Track",
        is_required: true,
        width: "half",
        options: [
          { value: "general_surgery", label: "General Surgery" },
          { value: "gynaecology", label: "Gynaecology" },
          { value: "urology", label: "Urology" },
          { value: "bariatric", label: "Bariatric Surgery" },
          { value: "robotics", label: "Robotic Surgery" },
          { value: "other", label: "Other" },
        ],
      },
      {
        field_type: "textarea",
        label: "Abstract Text",
        placeholder: "Include: Background, Methods, Results, and Conclusion (max 300 words)",
        help_text: "Structured abstract with Background, Methods, Results, and Conclusion",
        is_required: true,
        width: "full",
      },
      {
        field_type: "file",
        label: "Upload Abstract / Supporting File",
        help_text: "Upload PDF, Word document, or video file",
        is_required: false,
        width: "full",
      },
      {
        field_type: "checkbox",
        label: "I confirm this is original work and has not been published elsewhere",
        is_required: true,
        width: "full",
      },
    ],
  },
  {
    id: "volunteer-registration",
    name: "Volunteer Registration",
    description: "Registration form for event volunteers with availability and skill preferences",
    category: "event_registration",
    form_type: "event_registration",
    icon: "HeartHandshake",
    fields: [
      {
        field_type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        is_required: true,
        width: "half",
      },
      {
        field_type: "phone",
        label: "Phone Number",
        placeholder: "+91 9876543210",
        is_required: true,
        width: "half",
      },
      {
        field_type: "text",
        label: "Institution / College",
        placeholder: "Enter your institution name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "checkboxes",
        label: "Availability",
        help_text: "Select the days you are available",
        is_required: true,
        width: "full",
        options: [
          { value: "day_before", label: "Day Before (Setup)" },
          { value: "day_1", label: "Day 1" },
          { value: "day_2", label: "Day 2" },
          { value: "day_3", label: "Day 3" },
          { value: "all_days", label: "All Days" },
        ],
      },
      {
        field_type: "checkboxes",
        label: "Preferred Area",
        help_text: "Select areas where you'd like to help",
        is_required: true,
        width: "full",
        options: [
          { value: "registration_desk", label: "Registration Desk" },
          { value: "session_management", label: "Session / Hall Management" },
          { value: "speaker_coordination", label: "Speaker Coordination" },
          { value: "technical_av", label: "Technical / AV Support" },
          { value: "hospitality", label: "Hospitality / Food" },
          { value: "transport", label: "Transport / Logistics" },
          { value: "photography", label: "Photography / Social Media" },
          { value: "any", label: "Anywhere Needed" },
        ],
      },
      {
        field_type: "textarea",
        label: "Previous Volunteering Experience",
        placeholder: "Briefly describe any past volunteering experience (optional)",
        is_required: false,
        width: "full",
      },
      {
        field_type: "select",
        label: "T-Shirt Size",
        is_required: true,
        width: "half",
        options: [
          { value: "xs", label: "XS" },
          { value: "s", label: "S" },
          { value: "m", label: "M" },
          { value: "l", label: "L" },
          { value: "xl", label: "XL" },
          { value: "xxl", label: "XXL" },
        ],
      },
    ],
  },
  {
    id: "contact-inquiry",
    name: "Contact / Inquiry Form",
    description: "Simple contact form for general inquiries, support requests, and questions",
    category: "contact",
    form_type: "contact",
    icon: "Mail",
    fields: [
      {
        field_type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        is_required: true,
        width: "full",
      },
      {
        field_type: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        is_required: true,
        width: "half",
      },
      {
        field_type: "phone",
        label: "Phone Number",
        placeholder: "+91 9876543210",
        is_required: false,
        width: "half",
      },
      {
        field_type: "select",
        label: "Inquiry Type",
        is_required: true,
        width: "full",
        options: [
          { value: "registration", label: "Registration Help" },
          { value: "payment", label: "Payment Issue" },
          { value: "accommodation", label: "Accommodation" },
          { value: "travel", label: "Travel / Transport" },
          { value: "certificate", label: "Certificate" },
          { value: "sponsorship", label: "Sponsorship" },
          { value: "other", label: "Other" },
        ],
      },
      {
        field_type: "text",
        label: "Subject",
        placeholder: "Brief subject of your inquiry",
        is_required: true,
        width: "full",
      },
      {
        field_type: "textarea",
        label: "Message",
        placeholder: "Describe your inquiry in detail...",
        is_required: true,
        width: "full",
      },
    ],
  },
]

export function getTemplateById(id: string): FormTemplateDefinition | undefined {
  return FORM_TEMPLATES.find((t) => t.id === id)
}
