import nextCoreWebVitals from "eslint-config-next/core-web-vitals"
import nextTypescript from "eslint-config-next/typescript"

// Flat config, replacing .eslintrc.json.
//
// Why this changed: the project runs Next 16 but `eslint-config-next` was
// pinned at 14.2.21 with `eslint ^8`. That mismatch had two visible costs.
//
//   1. `npm run lint` was broken outright — it ran `next lint`, which Next 16
//      removed. The script now calls eslint directly.
//   2. Every rule the old config referenced — @typescript-eslint/*,
//      @next/next/*, jsx-a11y/* — arrived only TRANSITIVELY through
//      eslint-config-next. A checkout that resolves dependencies differently
//      (a scanner sandbox, a fresh CI image, a pnpm install with strict
//      hoisting) reports "Definition for rule '<x>' was not found" for every
//      `eslint-disable-next-line` comment naming one of those rules — ~520 of
//      them in this repo. Pinning eslint-config-next to the Next major and
//      importing its flat configs directly makes that resolution explicit.
//
// eslint-config-next v16 ships flat configs, so these are imported directly
// rather than wrapped in FlatCompat (which only understands eslintrc-shaped
// objects and throws a schema-validation error on them).
//
// Nothing in CI runs lint today (.github/workflows has only migrations.yml and
// rafter-security.yml), so this migration could not regress a pipeline.

export default [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      "build/**",
      "coverage/**",
      "next-env.d.ts",
      "src/lib/supabase/database.types.ts", // generated by `supabase gen types`
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      // Carried over verbatim from .eslintrc.json.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },
]
