import { requireAdmin } from '@/lib/auth/api-auth'
import { createAdminClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'
import { sendEmail, isEmailEnabled } from '@/lib/email'
import { COMPANY_CONFIG } from '@/lib/config'

// POST - Resend team invitation
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { user, error: authError } = await requireAdmin()
    if (authError) return authError
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { id } = await params

    const adminClientRaw = await createAdminClient()
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const supabase = adminClientRaw as any

    // Fetch the invitation
    const { data: invitation, error: fetchError } = await supabase
      .from('team_invitations')
      .select('*')
      .eq('id', id)
      .single()

    if (fetchError || !invitation) {
      return NextResponse.json(
        { error: 'Invitation not found' },
        { status: 404 }
      )
    }

    if (invitation.status !== 'pending') {
      return NextResponse.json(
        { error: `Cannot resend: invitation is ${invitation.status}` },
        { status: 400 }
      )
    }

    // If expired, refresh the expiration and generate a new token
    const now = new Date()
    const expiresAt = new Date(invitation.expires_at)
    const isExpired = expiresAt < now

    if (isExpired) {
      const newExpiresAt = new Date()
      newExpiresAt.setDate(newExpiresAt.getDate() + 7)

      // Update with new expiration; token is regenerated by DB default via gen_random_uuid()
      // We need to set a new token manually since update won't trigger the default
      const { data: updated, error: updateError } = await supabase
        .from('team_invitations')
        .update({
          expires_at: newExpiresAt.toISOString(),
          token: crypto.randomUUID(),
        })
        .eq('id', id)
        .select()
        .single()

      if (updateError) {
        console.error('Failed to refresh invitation:', updateError)
        return NextResponse.json(
          { error: 'Failed to refresh invitation' },
          { status: 500 }
        )
      }

      // Use the updated invitation for the email
      Object.assign(invitation, updated)
    }

    // Send the invitation email
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://collegeofmas.org.in'
    const inviteLink = `${appUrl}/team/accept-invite?token=${invitation.token}`

    if (isEmailEnabled()) {
      const emailResult = await sendEmail({
        to: invitation.email,
        subject: `Reminder: You're invited to join ${COMPANY_CONFIG.name} team`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>Team Invitation Reminder</h2>
            <p>Hi${invitation.name ? ` ${invitation.name}` : ''},</p>
            <p>This is a reminder that you have been invited to join the <strong>${COMPANY_CONFIG.name}</strong> team as <strong>${invitation.role}</strong>.</p>
            <p>Click the button below to accept the invitation:</p>
            <p style="margin: 24px 0;">
              <a href="${inviteLink}"
                 style="background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
                Accept Invitation
              </a>
            </p>
            <p style="color: #6b7280; font-size: 14px;">
              Or copy and paste this link: <br/>
              <a href="${inviteLink}">${inviteLink}</a>
            </p>
            <p style="color: #6b7280; font-size: 14px;">This invitation expires in 7 days.</p>
            <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;" />
            <p style="color: #9ca3af; font-size: 12px;">${COMPANY_CONFIG.fullName}</p>
          </div>
        `,
      })

      if (!emailResult.success) {
        console.error('Failed to resend invitation email:', emailResult.error)
        return NextResponse.json(
          { error: `Invitation exists but email failed to send: ${emailResult.error}` },
          { status: 500 }
        )
      }
    } else {
      console.warn('[Team Invite] Email not enabled. Invite link:', inviteLink)
    }

    return NextResponse.json({
      success: true,
      message: isExpired ? 'Invitation refreshed and resent' : 'Invitation resent',
      data: invitation,
    })
  } catch (error) {
    console.error('Resend invite API error:', error)
    return NextResponse.json(
      { error: 'Failed to resend invitation' },
      { status: 500 }
    )
  }
}
